security:
    encoders:
        App\Entity\Animator:
            algorithm: bcrypt
        App\Entity\Admin:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Animator
                property: email
        admin_entity:
            entity:
                class: App\Entity\Admin
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin
            http_basic: ~
            provider: admin_entity
            anonymous: ~
            form_login:
                login_path: /admin/login
                check_path: /admin/login
                target_path_parameter: /admin/index
            logout:
                path:   /admin/logout
                target: /admin/
        main:
            pattern: ^/
            http_basic: ~
            provider: app_user_provider
            anonymous: ~
            logout:
                path:   /wylogowanie
                target: /
            guard:
                authenticators:
                    - App\Security\AnimatorAuthenticator

    role_hierarchy:
        ROLE_ADMIN: ROLE_REDAKTOR
    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/animator, roles: ROLE_ANIMATOR }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
